// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWeNzKvRJUy22FxF5BDSNVCiT5rBgsJm0',
    appId: '1:671482888438:web:88e112a8bf3c184a652cd7',
    messagingSenderId: '671482888438',
    projectId: 'cins467-c8996',
    authDomain: 'cins467-c8996.firebaseapp.com',
    storageBucket: 'cins467-c8996.appspot.com',
    measurementId: 'G-PT9EWB7GVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkKsZy2kRdPaTWg8ryIueZXvKC22LI6U8',
    appId: '1:671482888438:android:bb32da8b145e92d8652cd7',
    messagingSenderId: '671482888438',
    projectId: 'cins467-c8996',
    storageBucket: 'cins467-c8996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCBMY4HpakCffny_gVWDApbCXElKt_nsA',
    appId: '1:671482888438:ios:1c7d61ef74aaae95652cd7',
    messagingSenderId: '671482888438',
    projectId: 'cins467-c8996',
    storageBucket: 'cins467-c8996.appspot.com',
    iosBundleId: 'com.example.petpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCBMY4HpakCffny_gVWDApbCXElKt_nsA',
    appId: '1:671482888438:ios:e633b9178bdff73f652cd7',
    messagingSenderId: '671482888438',
    projectId: 'cins467-c8996',
    storageBucket: 'cins467-c8996.appspot.com',
    iosBundleId: 'com.example.petpal.RunnerTests',
  );
}
